task: semantic_eval
data:
  base_dir: "../../Documents/数据集/CitySpaces"
  val_img_dir: "leftImg8bit_trainvaltest/leftImg8bit/val"
  val_label_dir: "gtFine_trainvaltest/gtFine/val"
  batch_size: 16
model:
  type: deeplabv3plus_mobilenet
  num_classes: 19
  pretrained_weights: "models/best_semantic_model.pth"
output:
  dir: "output/evaluation"
  save_results: false  # 是否保存分割结果图像
  save_confusion_matrix: true  # 是否保存混淆矩阵图
