task: sr_test
data:
  base_dir: "../../Documents/数据集/CitySpaces/leftImg8bit_trainvaltest/leftImg8bit"
  test_hr_dir: "test"
  test_lr_dir: "test_lr_x4"
  batch_size: 2
model:
  type: FeatureFusionSR
  semantic_model_path: "models/best_deeplabv3plus_mobilenet_cityscapes_os16.pth"
  model_path: "runs/run_20250319-0722/models/best_model.pth"
output:
  dir: "output/feature_fusion_sr"