task: sr_test_no_semantic
data:
  base_dir: "../../Documents/数据集/CitySpaces/leftImg8bit_trainvaltest/leftImg8bit"
  test_hr_dir: "test"
  test_lr_dir: "test_lr_x4"
  batch_size: 2
model:
  type: FeatureFusionSR_NoSemantic
  model_variant: "no_semantic"
  model_path: "runs/no_semantic_run_{DATE}/models/best_model.pth"
output:
  dir: "output/sr_no_semantic"
